### PR TITLE
new design and many other fixes

### PR DESCRIPTION
**Pull request by the-weird-aquarian**
- updated gradle plugin to 7.0.0 and gradle to 7.1.1
- updated dependencies
- new flat material design ui
- fixed card view icons placement
- changed all icons to material icons
- fixed toolbar title appearance & placement
- fixed some text colors
- fixed search bar color
- removed some nested layouts
- removed all ui warnings
- better dark mode colors
- new switch design
- new tab indicator design
- removed password toggle code in login screen as it is handled automatically now
- removed some unused icons

### CODE REVIEW

**Comment by ntnhon** [comment]
Hello, thank you for the PR! Actually on vacation I won't be able to review it before next week. It's one of the biggest PRs I've had to deal with 😄

**Comment by the-weird-aquarian** [comment]
> Hello, thank you for the PR! Actually on vacation I won't be able to review it before next week. It's one of the biggest PRs I've had to deal with smile

No issue. Enjoy your vacations. :smile:

**Review by ntnhon — APPROVED** [review]
Hello @the-weird-aquarian, first of all I'd like to say sorry for being late 🙏. The PR is quite large in term of number of files changed but it wasn't too complicated as changes are all UI related.

The new design looks great and is a lot more modern than the old one. Thanks to the PR I learnt that the `TextInputLayout` has `password_toggle` which offers nice transition animation between showing/hiding password mode. I also got to know that `RecyclerView` has `tools:listitem` attribute to help visualize the list with another layout as items placeholder.

I'll merge this and another fix (https://github.com/simple-login/Simple-Login-Android/pull/59) and then I'll make a new release asap.

For your information, I'll be working on rewriting this app in Jetpack Compose. It'll be a chance for me to adopt a more solid architecture and rework on the UI part. For now I'm actively working on rewriting/redesigning the iOS version in SwiftUI. It'd take me a while before I can come back to this Android version. So if you happen to do some iOS dev, be my guess here (https://github.com/simple-login/Simple-Login-iOS/tree/swiftui).

On behalf of the SimpleLogin team, I thank you so much for this great PR 🙏.

**Comment by the-weird-aquarian** [comment]
> The new design looks great and is a lot more modern than the old one.

Thank you for accepting the PR. I'm glad you find the new design better. :smile: 

> For your information, I'll be working on rewriting this app in Jetpack Compose. It'll be a chance for me to adopt a more solid architecture and rework on the UI part. For now I'm actively working on rewriting/redesigning the iOS version in SwiftUI. It'd take me a while before I can come back to this Android version. So if you happen to do some iOS dev, be my guest here (https://github.com/simple-login/Simple-Login-iOS/tree/swiftui).

Yes, Jetpack Compose and iOS dev has been on my learning list for quite some time now. Currently I only do android. Guess it's good time to start looking into Jetpack Compose and SwiftUI. Once I do I would definitely contribute to the other projects.

**Comment by ntnhon** [comment]
I'm using Jetpack Compose in a project at work and it feels so good. Definitely worth your time to learn. The update is accepted in both Play Store & F-droid.
Screen Shot 2021-09-14 at 09 50 16
Screen Shot 2021-09-14 at 09 50 38
See you in an another PR 😄

**Pull request merged**
